language: python
sudo: False
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- nightly # 3.6
env:
  matrix:
  - DJANGO=""
  - DJANGO="1.7"
  - DJANGO="1.8"
  - DJANGO="1.9"
  - DJANGO="1.10"

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- if [[ "${DJANGO}" ]]; then pip install "django==$DJANGO"; fi

matrix:
  exclude:
  # Exclude django < 1.9 when building with python 3.5
  # once  is fixed, change it to 1.7/1.8
  - python: "3.5"
    env: DJANGO="1.7"
  - python: "3.5"
    env: DJANGO="1.8"

    # Django 1.9+ no longer supports python 3.2/3.3
  - python: "3.2"
    env: DJANGO="1.7"
  - python: "3.2"
    env: DJANGO="1.8"
  - python: "3.2"
    env: DJANGO="1.9"

  - python: "3.3"
    env: DJANGO="1.7"
  - python: "3.3"
    env: DJANGO="1.8"
  - python: "3.3"
    env: DJANGO="1.9"

script: make travis

after_success:
- coveralls

#notifications:
#  irc:
#    channels: "chat.freenode.net#not-your-server.de"
#    template:
#    - "%{repository} - %{branch} - %{author}: %{commit_subject} - %{message} - Build details : %{build_url}"
#    use_notice: true
